// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSY2JzEhQILg0mN4g1dHEMlzjcUROCku0',
    appId: '1:561254843554:web:f6ffae08bffd1b974f43fb',
    messagingSenderId: '561254843554',
    projectId: 'tiktok-clone-sjiw',
    authDomain: 'tiktok-clone-sjiw.firebaseapp.com',
    storageBucket: 'tiktok-clone-sjiw.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf0C-E2pb_f6wy1yGaDE5Xsp6XVk-Qua0',
    appId: '1:561254843554:android:b0e7f66766eb92154f43fb',
    messagingSenderId: '561254843554',
    projectId: 'tiktok-clone-sjiw',
    storageBucket: 'tiktok-clone-sjiw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSigoYs3sFbRbca1yBBowqUEbUtA_tm8k',
    appId: '1:561254843554:ios:2f83ed270e3beeef4f43fb',
    messagingSenderId: '561254843554',
    projectId: 'tiktok-clone-sjiw',
    storageBucket: 'tiktok-clone-sjiw.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClone',
  );

}